import type { Metadata } from "next";
import "./globals.css";
import HeaderTop from "@/components/HeaderTop";



export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <HeaderTop/>
        {children}
      </body>
    </html>
  );
}
